#!/usr/bin/env bash
# This script displays "Best school" 9 times and hi for the 9th iteration using a while 
c=0
while [ $c -le 10 ]
do
  if [ $c -eq 9 ]
  then
     echo "Hi"
 else
   echo "Best School"
 fi  
c=$((c+1))
done   