#!/usr/bin/env bash
# This script displays "Best school" 9 times and hi for the 9th iteration using a while 
c=1
while [ $c -le 10 ]
do
  if [ $c -eq 4 ]
  then
     echo "bad luck"
  elif [ $c -eq  8 ]
  then
     echo "good luck"   
 else
   echo "Best School"
 fi  
c=$((c+1))
done   