#!/usr/bin/env bash
# This script iterates from 1 to 10 and displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
while [ $c -le 10 ]
do
  if [ $c -eq 4 ]
  then
     echo "bad luck"
  elif [ $c -eq  8 ]
  then
     echo "good luck"   
 else
   echo "Best School"
 fi  
c=$((c+1))
done   